[project]
name = "pixi-update-test"
version = "0.1.0"
description = "Add a short description here"
authors = ["Julian Hofer <julianhofer@gnome.org>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = "3.10.*"

[pypi-dependencies]
numpy = "==1.*"
